In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv("../data/raw/ipl_matches_data.csv")
df

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,venue,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,result,player_of_match
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,M Chinnaswamy Stadium,1,1,6,field,6,140.0,NaN,win,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,"Rajiv Gandhi International Stadium, Uppal",1,2,1,field,2,35.0,NaN,win,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Maharashtra Cricket Association Stadium,4,4,3,field,4,NaN,7.0,win,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Saurashtra Cricket Association Stadium,6,5,6,field,6,NaN,10.0,win,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Holkar Cricket Stadium,494,494,4,field,494,NaN,6.0,win,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,2026,6,Delhi,2026-04-27,Indian Premier League,39.0,male,T20,T20,...,"Arun Jaitley Stadium, Delhi",1,252,1,field,1,NaN,9.0,win,4664.0
1208,1529283,2026,6,New Chandigarh,2026-04-28,Indian Premier League,40.0,male,T20,T20,...,Maharaja Yadavindra Singh International Cricke...,134,494,134,field,134,NaN,6.0,win,11389.0
1209,1529284,2026,6,Mumbai,2026-04-29,Indian Premier League,41.0,male,T20,T20,...,"Wankhede Stadium, Mumbai",3,3,2,bat,2,NaN,6.0,win,1740.0
1210,1529285,2026,6,Ahmedabad,2026-04-30,Indian Premier League,42.0,male,T20,T20,...,"Narendra Modi Stadium, Ahmedabad",615,1,615,field,615,NaN,4.0,win,4098.0
1211,1529286,2026,6,Jaipur,2026-05-01,Indian Premier League,43.0,male,T20,T20,...,"Sawai Mansingh Stadium, Jaipur",134,134,252,bat,252,NaN,7.0,win,1409.0

Select the relevant columns

In [4]:
relevant_columns = [
    "match_id",
    "season_id",
    "match_date",
    "city",
    "venue",
    "toss_winner",
    "team1",
    "team2",
    "toss_decision",
    "match_winner",
    "result",
]

df=df[relevant_columns]
df

,match_id,season_id,match_date,city,venue,toss_winner,team1,team2,toss_decision,match_winner,result
0,335982,2008,2008-04-18,Bangalore,M Chinnaswamy Stadium,1,1,6,field,6,win
1,1082591,2017,2017-04-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",1,2,1,field,2,win
2,1082592,2017,2017-04-06,Pune,Maharashtra Cricket Association Stadium,4,4,3,field,4,win
3,1082593,2017,2017-04-07,Rajkot,Saurashtra Cricket Association Stadium,6,5,6,field,6,win
4,1082594,2017,2017-04-08,Indore,Holkar Cricket Stadium,494,494,4,field,494,win
...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,2026,2026-04-27,Delhi,"Arun Jaitley Stadium, Delhi",1,252,1,field,1,win
1208,1529283,2026,2026-04-28,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,134,494,134,field,134,win
1209,1529284,2026,2026-04-29,Mumbai,"Wankhede Stadium, Mumbai",3,3,2,bat,2,win
1210,1529285,2026,2026-04-30,Ahmedabad,"Narendra Modi Stadium, Ahmedabad",615,1,615,field,615,win
1211,1529286,2026,2026-05-01,Jaipur,"Sawai Mansingh Stadium, Jaipur",134,134,252,bat,252,win

Now, we first calculate the total runs from the ball by ball dataset to calculate whats the total target a team is chasing i.e calculate the total score for 1st innings. And then merge them into the above reduced dataframe

In [10]:
df2=pd.read_csv("../data/raw/ball_by_ball_data.csv")

first_innings=(
    df2[df2["innings"]==1]
    .groupby("match_id")["total_runs"]
    .sum()
    .reset_index()
)

first_innings

      match_id  total_runs
0       335982         222
1       335983         240
2       335984         129
3       335985         165
4       335986         110
...        ...         ...
1207   1529282          75
1208   1529283         222
1209   1529284         243
1210   1529285         155
1211   1529286         225

[1212 rows x 2 columns]

In [11]:
df=df.merge(first_innings, on="match_id", how="left")
df

,match_id,season_id,match_date,city,venue,toss_winner,team1,team2,toss_decision,match_winner,result,total_runs
0,335982,2008,2008-04-18,Bangalore,M Chinnaswamy Stadium,1,1,6,field,6,win,222
1,1082591,2017,2017-04-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",1,2,1,field,2,win,207
2,1082592,2017,2017-04-06,Pune,Maharashtra Cricket Association Stadium,4,4,3,field,4,win,184
3,1082593,2017,2017-04-07,Rajkot,Saurashtra Cricket Association Stadium,6,5,6,field,6,win,183
4,1082594,2017,2017-04-08,Indore,Holkar Cricket Stadium,494,494,4,field,494,win,163
...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,2026,2026-04-27,Delhi,"Arun Jaitley Stadium, Delhi",1,252,1,field,1,win,75
1208,1529283,2026,2026-04-28,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,134,494,134,field,134,win,222
1209,1529284,2026,2026-04-29,Mumbai,"Wankhede Stadium, Mumbai",3,3,2,bat,2,win,243
1210,1529285,2026,2026-04-30,Ahmedabad,"Narendra Modi Stadium, Ahmedabad",615,1,615,field,615,win,155
1211,1529286,2026,2026-05-01,Jaipur,"Sawai Mansingh Stadium, Jaipur",134,134,252,bat,252,win,225